steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t asia-northeast1-docker.pkg.dev/$PROJECT_ID/hotoku-batch/quickstart-image:tag1 .
  automapSubstitutions: true
images:
- 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/hotoku-batch/quickstart-image:tag1'
